sudo: required
services:
  - docker

before_install:
  - docker build -t levonbaghdasaryan/docker-react -f Dockerfile.dev .

script:
  - docker run levonbaghdasaryan/docker-react npm run test -- - -coverage